# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: cosmos-db-nosql-nodejs-quickstart
metadata:
  template: cosmos-db-nosql-nodejs-quickstart
services:
  javascript-web:
    project: ./src/js
    language: js
    host: appservice
  typescript-web:
    project: ./src/ts
    language: js
    host: appservice
pipeline:
  provider: github
hooks:
  postprovision:
    windows:
      shell: pwsh
      run: |
        echo "AZURE_COSMOS_DB_NOSQL_ENDPOINT=""$env:AZURE_COSMOS_DB_NOSQL_ENDPOINT""" > ./src/js/.env
        echo "AZURE_COSMOS_DB_NOSQL_ENDPOINT=""$env:AZURE_COSMOS_DB_NOSQL_ENDPOINT""" > ./src/ts/.env
      continueOnError: false
      interactive: true
    posix:
      shell: sh
      run: |
        echo "AZURE_COSMOS_DB_NOSQL_ENDPOINT=\"$AZURE_COSMOS_DB_NOSQL_ENDPOINT\"" > ./src/js/.env
        echo "AZURE_COSMOS_DB_NOSQL_ENDPOINT=\"$AZURE_COSMOS_DB_NOSQL_ENDPOINT\"" > ./src/ts/.env
      continueOnError: false
      interactive: true