name: Validate Node.js solution
on:
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  validate-python:
    name: Validate Node.js solution
    runs-on: ubuntu-latest
    container: 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4     
      - name: Check Node.js version
        run: node --version         
      - name: Check NPM version
        run: npm --version   
      - name: Install NPM packages
        run: npm install
        working-directory: ./src